/******************************************************************************
* Copyright (C) 2023 Advanced Micro Devices, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT
******************************************************************************/
/*
 * helloworld.c: simple test application
 *
 * This application configures UART 16550 to baud rate 9600.
 * PS7 UART (Zynq) is not initialized by this application, since
 * bootrom/bsp configures it to baud rate 115200
 *
 * ------------------------------------------------
 * | UART TYPE   BAUD RATE                        |
 * ------------------------------------------------
 *   uartns550   9600
 *   uartlite    Configurable only in HW design
 *   ps7_uart    115200 (configured by bootrom/bsp)
 */

#include <stdio.h>
#include "platform.h"
#include "xil_printf.h"
#include "xgpio.h"
#include "xparameters.h"

// Note: XPAR_GPIO_SW_DEVICE_ID and XPAR_GPIO_LED_DEVICE_ID are defined in
// xparameters.h, which is generated by the hardware platform design.

// Global XGpio instances for the switches and LEDs
XGpio sw_gpio;
XGpio led_gpio;

/*
 * This function initializes both the Switch GPIO and LED GPIO peripherals.
 * It also sets the data direction: switches are input, LEDs are output.
 */
void driverInit()
{
    int Status;

    // --- Switch GPIO Initialization ---
    print("Initialization of switch gpio\r\n");
    Status = XGpio_Initialize(&sw_gpio, XPAR_GPIO_SW_BASEADDR);
    if (Status != XST_SUCCESS) {
        print("Failed!\n\r");
       
    } else {
        print("Success!\n\r");
        XGpio_SetDataDirection(&sw_gpio, 1, 1);

    }

    // --- LED GPIO Initialization ---
    print("Initialization of led gpio\r\n");
    Status = XGpio_Initialize(&led_gpio, XPAR_AXI_GPIO_0_BASEADDR);
    if (Status != XST_SUCCESS) {
        print("Failed!\n\r");
    } else {
        print("Success!\n\r");

        // Set the LED GPIO channel 1 to be output (direction mask of 0x0000 is all outputs)
        XGpio_SetDataDirection(&led_gpio, 1, 0);

        // Initial state: ensure all LEDs are off
        XGpio_DiscreteWrite(&led_gpio, 1, 0);
    }

}


int main()
{
    int sw_val;

    init_platform();
    print("Hello World \n\r");

    driverInit();
    print("Running GPIO\n\r");



    while(1)
    {
        // Read the 16-bit value from GPIO Channel 1 (the switches)
        sw_val = XGpio_DiscreteRead(&sw_gpio, 1);

        // This switch/case structure only handles one switch being ON at a time.
        // If 'sw' value does not match one of the single-bit masks (0x0001, 0x0002, etc.),
        // it falls through to the 'default' case and turns off all LEDs.
        switch(sw_val)
        {
            case 0: // Switch 0 is ON
                XGpio_DiscreteWrite(&led_gpio, 1, 0x0000);
                break;
            case 1: // Switch 1 is ON
                XGpio_DiscreteWrite(&led_gpio, 1, 0x0001);
                break;
            case 2: // Switch 2 is ON
                XGpio_DiscreteWrite(&led_gpio, 1, 0x0002);
                break;
            case 4: // Switch 3 is ON
                XGpio_DiscreteWrite(&led_gpio, 1, 0x0004);
                break;
            case 8: // Switch 4 is ON (Extending the pattern)
                XGpio_DiscreteWrite(&led_gpio, 1, 0x0008);
                break;

            default:
                break;
        }

    }

    cleanup_platform();
    return 0;
}
